# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.climbing_stairs as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 117
    set_0 = {int_0}
    var_0 = module_0.climb_stairs(int_0)
    assert var_0 == 2046711111473984623691759
    set_1 = set()
    int_1 = 1658
    list_0 = [set_0, int_0, set_1, int_1]
    module_0.climb_stairs(list_0)


def test_case_1():
    bool_0 = True
    var_0 = module_0.climb_stairs_optimized(bool_0)
    assert var_0 == 1
