# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.coin_change as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    tuple_0 = (bool_0, bool_0)
    var_0 = module_0.count(tuple_0, bool_0)
    assert var_0 == 4
    str_0 = 'Myn"B3\n'
    module_0.count(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    float_0 = -1894.330712
    module_0.count(float_0, float_0)
