# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.int_divide as module_0
import builtins as module_1


def test_case_0():
    bool_0 = True
    var_0 = module_0.int_divide(bool_0)
    assert var_0 == 1
    var_1 = module_0.int_divide(var_0)
    assert var_1 == 1


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -767
    module_0.int_divide(int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.int_divide(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    var_0 = module_0.int_divide(bool_0)
    assert var_0 == 1
    int_0 = 505
    var_1 = module_1.object()
    var_2 = module_0.int_divide(bool_0)
    assert var_2 == 1
    var_3 = module_0.int_divide(int_0)
    assert var_3 == 3031941282464413132742
    module_0.int_divide(var_1)
