# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.house_robber as module_0
import builtins as module_1


def test_case_0():
    bytes_0 = b"\x9es\xef\xf6\x8bmc\x85!-\xa8\xcc\rS\x0e\xfd\x97\x81"
    var_0 = module_0.house_robber(bytes_0)
    assert var_0 == 1383
    var_1 = module_0.house_robber(bytes_0)
    assert var_1 == 1383


@pytest.mark.xfail(strict=True)
def test_case_1():
    object_0 = module_1.object()
    module_0.house_robber(object_0)
