# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.graph.count_connected_number_of_component as module_0


def test_case_0():
    bool_0 = False
    var_0 = module_0.count_components(bool_0, bool_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 2668
    module_0.count_components(int_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    str_0 = "|#2o\x0cN%0c\\UF|\x0b\tv,z"
    module_0.count_components(str_0, bool_0)


def test_case_3():
    bool_0 = True
    dict_0 = {
        bool_0: bool_0,
        bool_0: bool_0,
        bool_0: bool_0,
        bool_0: bool_0,
        bool_0: bool_0,
    }
    tuple_0 = (bool_0, dict_0, bool_0, bool_0)
    var_0 = module_0.count_components(tuple_0, bool_0)
    assert var_0 == 1


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = False
    dict_0 = {bool_0: bool_0, bool_0: bool_0, bool_0: bool_0}
    bool_1 = True
    tuple_0 = (bool_0, dict_0, bool_1, bool_0)
    module_0.count_components(tuple_0, bool_1)
