# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.graph.check_digraph_strongly_connected as module_0


def test_case_0():
    bool_0 = True
    graph_0 = module_0.Graph(bool_0)
    var_0 = graph_0.is_strongly_connected()
    assert var_0 is True
    assert len(graph_0.graph) == 1


def test_case_1():
    int_0 = 134
    graph_0 = module_0.Graph(int_0)
    var_0 = graph_0.is_strongly_connected()
    assert var_0 is False
    assert len(graph_0.graph) == 1


def test_case_2():
    bool_0 = True
    graph_0 = module_0.Graph(bool_0)


def test_case_3():
    bool_0 = True
    graph_0 = module_0.Graph(bool_0)
    bool_1 = False
    var_0 = graph_0.add_edge(bool_1, bool_1)
    var_1 = graph_0.is_strongly_connected()
    assert var_1 is True
