# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.egg_drop as module_0


def test_case_0():
    bool_0 = False
    var_0 = module_0.egg_drop(bool_0, bool_0)
    assert var_0 == 0
    assert module_0.INT_MAX == 32767


def test_case_1():
    bool_0 = True
    var_0 = module_0.egg_drop(bool_0, bool_0)
    assert var_0 == 1
    assert module_0.INT_MAX == 32767


def test_case_2():
    bool_0 = True
    int_0 = 1232
    var_0 = module_0.egg_drop(int_0, bool_0)
    assert var_0 == 1
    assert module_0.INT_MAX == 32767


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = 78
    var_0 = module_0.egg_drop(int_0, int_0)
    assert var_0 == 7
    assert module_0.INT_MAX == 32767
    bool_0 = True
    var_1 = module_0.egg_drop(int_0, bool_0)
    assert var_1 == 1
    int_1 = 104
    none_type_0 = None
    module_0.egg_drop(int_1, none_type_0)
